apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation
  template:
    metadata:
      labels:
        app: geolocation
    spec:
      containers:
      - name: geolocation
        image: container_image  # This will be replaced by the Jenkins pipeline
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: geolocation
  namespace: default
spec:
  selector:
    app: geolocation
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP

